services:
  db:
    image: postgres:latest
    container_name: test-task-chat-db
    environment:
      POSTGRES_USER: test_task_chat
      POSTGRES_PASSWORD: test_task_chat
      POSTGRES_DB: test_task_chat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-task-chat
    env_file:
      - .env
    environment:
      - PG_HOST=test-task-chat-db
    ports:
      - "8080:8080"
    volumes:
      - .:/data
    working_dir: /data
    depends_on:
      - db

volumes:
  pgdata:
